name: "Basic"

on: ['push', 'pull_request']

env:
  GLOBAL_VALUE: "This is a env variable from the GLOBAL level"

jobs:
  first:
    if: github.event_name == 'pull_request'
    name: "First Job"

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ['16.x', '18.x']

    runs-on: ${{matrix.os}}

    env:
      JOB_VALUE_1: "This is a env variable from the JOB level #1"

    steps:
      - name: Say Hello from OS - ${{matrix.os}}
        shell: bash
        run: |
          echo "Hello World from ${{matrix.os}}"
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}
      - name: Run only on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          echo "Hello from ${{matrix.os}}"