name: "Basic"

on:
  push:
    branches:
      - main
jobs:
  somabot:
    name: "소마 봇으로 메시지 보내기"
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Webex space
        shell: bash
        run: |
          curl --location --request POST "https://webexapis.com/v1/messages" \
          --header "Content-Type: application/json" \
          --header "Authorization: Bearer ${{ secrets.WEBEX_TOKEN }}" \
          --data-raw '{
            "roomId": "${{ secrets.WEBEX_ROOM_ID }}",
            "text": "깃헙 액션으로 메시지 보내기"
          }'